all:
	cd ./quic-go-rtc/server/; go build
	cd ./quic-go-rtc/client/; go build
	cd ./quic-go-goodput/server/; go build
	cd ./quic-go-goodput/client/; go build


clean:
	rm -f ./quic-go-rtc/server/server ./quic-go-rtc/client/client ./quic-go-goodput/server/server ./quic-go-goodput/client/client
